ALTER TYPE "SupportCaseStatus" ADD VALUE IF NOT EXISTS 'PERMANENT_DIGITAL_TRANSFER_REQUESTED';

ALTER TYPE "SupportCaseResolution" ADD VALUE IF NOT EXISTS 'TEMPORARY_DIGITAL_TRANSFER';
ALTER TYPE "SupportCaseResolution" ADD VALUE IF NOT EXISTS 'REPLACEMENT_CARD';
ALTER TYPE "SupportCaseResolution" ADD VALUE IF NOT EXISTS 'PERMANENT_DIGITAL_TRANSFER';
